schema_version = "1.1.0"
id = "nano_banana"
version = "0.5.0"
name = "Nano-Banana (Gemini Image) Editor"
tagline = "Gemini 2.5 Flash image editor"
type = "add-on"
blender_version_min = "4.3.0"
license = ["MIT"]
author = "あなた"
permissions = ["network"]
