schema_version = "1.0.0"

id = "nano_banana"
version = "0.4.0"
name = "Nano-Banana (Gemini 2.5 Flash Image) Editor"
tagline = "Gemini 2.5 Flash Image add-on"
maintainer = "あなた"
type = "add-on"
blender_version_min = "4.0.0"
license = "GPL-3.0-or-later"
